### ISSUE TITLE
broken test

### ISSUE THREAD

**Issue by devisnik** [candrews/HttpResponseCache#1]
I get the follow error:

junit.framework.AssertionFailedError: expected:<[a=FIRST]> but was:<[]>
    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpResponseCacheTest.assertCookies(HttpResponseCacheTest.java:1582)
    at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpResponseCacheTest.testCachePlusCookies(HttpResponseCacheTest.java:1494)

Great work though!

**Comment by devisnik** [comment]
This seems to be caused by " domain=.local;" in the cookie. Removing this fixed the problem for me.

**Comment by candrews** [comment]
I don't get the error, but I'll try to reproduce it and fix it.

What OS and what version of Java are you using?

**Comment by devisnik** [comment]
I use Java6 on MacOS 10.6.8.

**Comment by candrews** [comment]
I believe this issue is fixed in ec2b98aed81af1145ebad527fe96bbaae323de0c - let me know if it isn't and I can re-open this issue.
