### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by tprochazka** [candrews/HttpResponseCache#24]
I just published first app which use httpresponsecache and I start receiving this error from Crittercism. I'm not able to reproduce it, it look that all reports are from Samsung Galaxy S II phone so far, but I'm not able to recognize if this is official ROM :-(

I use 1.2 version.
I looks that this happen only for HTTPS connections.
Maybe problem is not directly in httpresponsecache  but in security provider.

Has someone found similar problem?

`java.lang.ArrayIndexOutOfBoundsException: src.length=20 srcPos=20 dst.length=1024 dstPos=0 length=8
 at java.lang.System.arraycopy(Native Method)
 at org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl.engineNextBytes(SHA1PRNG_SecureRandomImpl.java:339)
 at org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl.engineGenerateSeed(SHA1PRNG_SecureRandomImpl.java:247)
 at java.security.SecureRandom.generateSeed(SecureRandom.java:348)
 at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:363)
 at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:218)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:480)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:435)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:293)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:243)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:84)
 at com.integralblue.httpresponsecache.compat.libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)`

**Comment by candrews** [comment]
What version of Android is the troublemaker device using?

**Comment by tprochazka** [comment]
I looks like 2.3.5 only
